version: '3.5'

services:
  ubuntu:
    image: my-ubuntu:1.0
    restart: always
    volumes:
      - static:/app/

  nginx:
    image: my-nginx:1.0
    restart: always
    ports:
      - "8005:80"
    volumes:
      - static:/etc/nginx/app/
volumes:
  static:
    driver: local
  